language: node_js
node_js:
- '0.10'
notifications:
  email: false
  slack:
    secure: fX5alHaT2lZlC5SN6kwTE3qzZRgDfmQkjQbZE/XPpJ9PGENtZOMq3pcBysSxEFl1JyNZzPeFEHyiaf77ffn4qS4kSlfz2PZ6+OYi6PTUEuKKTTgCOJjbGDQeHfKpKMwgnvt8VTAhBgCZzXKXs6ApwsrDY1pBRo4dp56x8FvbCbE=
before_install:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  on:
    all_branches: true
    tags: true
  api_key:
    secure: dYQ+xvF/xxGhIfUi5X7V7gmkM/BFfTOVLqiIEltnUMord+mNjPiy2KmD17cm3YIDxiIrdzGuGcm2TdOhagw/gpo4Fd8b8N1YA6FETZcllfzs7qMZU73FixTKtRkkyM5GG10QMnpJ+SQPyPDkBQyCsPIgSVUFrfKWAxnKoCd7R+c=
env:
  global:
  - secure: P4eIljp4LrxfOXp02Kg10kgEAP0pt2smoi3AzMzzBj0r4nSD+g6ipStaYXIjhfWqV2lAqDN7wdGnNQu7HDB/ZQfIV/kdvViXw7pfvQIoGMFPvxCQi1y1bIK7+cprwNhXyZh0V6bIcigfp4tzfZClAdYZXmr1wQW1Mv/9jQvh3fk=
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
sudo: false
cache:
  directories:
  - node_modules
