language: node_js
node_js:
- '0.10'
notifications:
  email: false
before_install:
- npm install -g grunt-cli
after_success:
- grunt ghrelease
deploy:
  provider: npm
  email: stephan@boennemann.me
  api_key:
    secure: MgWj/Ojy1S8/cw89n6yP/JCge4dEV0zPKM1L0z5fHyh3myP5c6vhqwmnlJsz88i1yjgSkEbqAZ3z6LYnU19QctjIiAeSjI2gplyk684QeiXJdLdlhL5PvOPkutjyqFbetKsQTto7q/4/Rl5XlmbHEoRNQ0+gE73eL+QROKdpD00=
  on:
    all_branches: true
    tags: true
env:
  global:
    secure: Bv7/uz9s9JMVuyiS8eiAV+/fT8Adh1WrXjQ4rad8WzBEgSI67P3fKvoKnSWdoNSY8f+Xe+VKwuWwMYGGYcDk8cHIYz7XV6Aud2GoApyj8hsHGX6s1zz0nDPc85zz4O5AYjRgf8r4F+L19LGzLEg8U3iYKm4bWj/Fb8wvfh7xPm0=
